#!/bin/bash
# simple script to scrap some of the Ceph tools and ship it up to Influxdb
# This requires jq to be installed @ /usr/bin/jq
# Usage: ceph-stats-influx <hostname of system> <number of ceph pools to scan> <influxdb url>

os_influx_write=$(mktemp /tmp/influx.XXXXXXXXX)

hyper_list=$(mktemp /tmp/hlist.XXXXXXXXX)
hyper_stats=$(mktemp /tmp/hstats.XXXXXXXXX)
floating_stats=$(mktemp /tmp/fstats.XXXXXXXXX)

/usr/local/bin/openstack --os-cloud admin hypervisor list -f json 	> $hyper_list
/usr/local/bin/openstack --os-cloud admin hypervisor stats show -f json > $hyper_stats
/usr/local/bin/openstack --os-cloud admin floating ip list -f json	> $floating_stats 

# Pass the hostname via the command line
CLOUDNAME=$1

# Find the number of Hypervisors we have and then loop over the results
# Sadly there is no way to run a single command and get ALL of the info at once.
# So we have to issue multiple openstack commands which isn't ideal... 
# But we will still only do this once per hypervisor
NUM_HYPERVISORS=$(/usr/bin/jq "length" $hyper_list )
for ((x=0; x<NUM_HYPERVISORS; x++)); do
	HYPER_ID=$(/usr/bin/jq ".[$x].ID" 		$hyper_list)
	hloop=$(mktemp /tmp/hloop.XXXXXXXXX)
	/usr/local/bin/openstack --os-cloud admin hypervisor show $HYPER_ID -f json > $hloop

	HYPER_NAME=$(/usr/bin/jq ".hypervisor_hostname" $hloop | tr -d \" )
	VCPU_USED=$(/usr/bin/jq ".vcpus_used" 		$hloop )
	VCPU_PHY=$(/usr/bin/jq ".vcpus_used" 		$hloop )
	VMS=$(/usr/bin/jq ".running_vms" 		$hloop )
	FREE_MEM_MB=$(/usr/bin/jq ".free_ram_mb" 	$hloop )
	USED_MEM_MB=$(/usr/bin/jq ".memory_mb_used" 	$hloop )
	MEM_MB_PHY=$(/usr/bin/jq ".memory_mb" 		$hloop )
	STATE=$(/usr/bin/jq -r ".state" $hloop | grep -c "up")

	echo "os_hypervisor_vms,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$VMS" 		>> $os_influx_write 
	echo "os_hypervisor_vcpu_phy,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$VCPU_PHY" 	>> $os_influx_write 
	echo "os_hypervisor_vcpu,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$VCPU_USED" 	>> $os_influx_write 
	echo "os_hypervisor_free_mb,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$FREE_MEM_MB"	>> $os_influx_write 
	echo "os_hypervisor_used_mb,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$USED_MEM_MB"	>> $os_influx_write 
	echo "os_hypervisor_mb_phy,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$MEM_MB_PHY" 	>> $os_influx_write 
	echo "os_hypervisor_state,Hypervisor=$HYPER_NAME,cloud=$CLOUDNAME value=$STATE" 	>> $os_influx_write 

	rm $hloop 
done

TOTAL_VCPU=$(/usr/bin/jq 	".vcpus"		$hyper_stats)
TOTAL_VCPU_USED=$(/usr/bin/jq 	".vcpus_used"		$hyper_stats)
TOTAL_MB=$(/usr/bin/jq 		".memory_mb"		$hyper_stats)
TOTAL_MB_FREE=$(/usr/bin/jq 	".free_ram_mb"		$hyper_stats)
TOTAL_MB_USED=$(/usr/bin/jq 	".memory_mb_used"	$hyper_stats)
TOTAL_VMS=$(/usr/bin/jq 	".running_vms"		$hyper_stats)
TOTAL_FLOATING_IP=$(/usr/bin/jq --raw-output '.[]."Floating IP Address"' $floating_stats   | wc -l)
PUBLIC_FLOATING_IP=$(/usr/bin/jq --raw-output '.[]."Floating IP Address"' $floating_stats  | grep -c 205.159.243)
PRIVATE_FLOATING_IP=$(/usr/bin/jq --raw-output '.[]."Floating IP Address"' $floating_stats | grep -c 10.30)

echo "os_total_vcpu,cloud=$CLOUDNAME value=$TOTAL_VCPU"			>> $os_influx_write
echo "os_total_vcpu_used,cloud=$CLOUDNAME value=$TOTAL_VCPU_USED"	>> $os_influx_write
echo "os_total_mb,cloud=$CLOUDNAME value=$TOTAL_MB"			>> $os_influx_write
echo "os_total_mb_free,cloud=$CLOUDNAME value=$TOTAL_MB_FREE"		>> $os_influx_write
echo "os_total_mb_used,cloud=$CLOUDNAME value=$TOTAL_MB_USED"		>> $os_influx_write
echo "os_total_vms,cloud=$CLOUDNAME value=$TOTAL_VMS"			>> $os_influx_write
echo "os_total_floating,cloud=$CLOUDNAME value=$TOTAL_FLOATING_IP"	>> $os_influx_write
echo "os_private_floating,cloud=$CLOUDNAME value=$PRIVATE_FLOATING_IP"	>> $os_influx_write
echo "os_public_floating,cloud=$CLOUDNAME value=$PUBLIC_FLOATING_IP"	>> $os_influx_write


# post the data to the database
POST="curl -i -XPOST \""$2\"" --data-binary @$os_influx_write"
eval $POST

# clean up the processed files.
rm $os_influx_write
rm $hyper_list
rm $hyper_stats
rm $floating_stats
