#!/bin/bash
# simple script to scrape Ups status from tripplite Ups and ship it up to Influxdb
HOSTNAME="upsmon1.imagestream.com"


/bin/upsc triplite> /tmp/ups-status

# Are we on Line Voltage?
LINEPOWER=$(cat /tmp/ups-status | grep -c "ups.status: OL")
# Line Voltage
LINEVOLTAGE=$(cat /tmp/ups-status | grep  "input.voltage:"  | awk '{print $2}')
# Battery Capacity 
BATTERYCAP=$(cat /tmp/ups-status | grep  "Battery Cap"  | awk '{print $3}')
# Runtime
UPSRUNTIME=$(cat /tmp/ups-status | grep  "Runtime"  | awk '{print $3}')
# Load in Watts
WATTS=$(cat /tmp/ups-status | grep  "Load"  | awk '{print $2}')


# Are we on Wall Power
echo "linepower,Hostname=$HOSTNAME value=$LINEPOWER" >> /tmp/influx_write
# Line Voltage
echo "linevoltage,Hostname=$HOSTNAME value=$LINEVOLTAGE" >> /tmp/influx_write
# Battery Capacity 1-100%
echo "ups_capacity,Hostname=$HOSTNAME value=$BATTERYCAP" >> /tmp/influx_write
# UPS Runtime in Minutes
echo "ups_runtime,Hostname=$HOSTNAME value=$UPSRUNTIME" >> /tmp/influx_write
# Load in Watts
echo "ups_load_watts,Hostname=$HOSTNAME value=$WATTS" >> /tmp/influx_write


# post the data to the database
#POST="curl -i -XPOST 'http://monitoring.imagestream.com:8086/write?db=imagestream' --data-binary @/tmp/influx_write"
#eval $POST

# clean up the processed files.
rm /tmp/ups-status
rm /tmp/influx_write

