#!/bin/bash
# simple script to scrape Ups status from tripplite Ups and ship it up to Influxdb
# usage: command <local hostname> <Url to the Influxdb>
HOSTNAME=$1


rm /tmp/ups-status
/bin/upsc triplight > /tmp/ups-status

# Are we on Line Voltage? If we should see status "OL" for On Line.  
LINEPOWER=$(cat /tmp/ups-status | grep -c "ups.status: OL")
# Line Voltage
LINEVOLTAGE=$(cat /tmp/ups-status | grep  "input.voltage:"  | awk '{print $2}')
# Battery Capacity 
BATTERYCAP=$(cat /tmp/ups-status | grep  "battery.charge:"  | awk '{print $2}')
# Runtime
UPSRUNTIME=$(cat /tmp/ups-status | grep  "battery.runtime:"  | awk '{print $2}')
# Load in Watts
LOADPERCENT=$(cat /tmp/ups-status | grep  "ups.load:"  | awk '{print $2}')
# Output in amps
OUTPUTAMPS=$(cat /tmp/ups-status | grep "output.current:" | awk '{print $2}')
# Battery Temp
BATTERYTEMP=$(cat /tmp/ups-status | grep  "battery.temperature:"  | awk '{print $2}')
# Battery Voltage 
BATTERYVOLT=$(cat /tmp/ups-status | grep  "battery.voltage:"  | awk '{print $2}')


# Are we on Wall Power
echo "linepower,Hostname=$HOSTNAME value=$LINEPOWER" >> /tmp/influx_write
# Line Voltage
echo "linevoltage,Hostname=$HOSTNAME value=$LINEVOLTAGE" >> /tmp/influx_write
# Battery Capacity 1-100%
echo "ups_capacity,Hostname=$HOSTNAME value=$BATTERYCAP" >> /tmp/influx_write
# UPS Runtime in seconds
echo "ups_runtime,Hostname=$HOSTNAME value=$UPSRUNTIME" >> /tmp/influx_write
# Load in Watts
echo "ups_load_percent,Hostname=$HOSTNAME value=$LOADPERCENT" >> /tmp/influx_write
# Ups power output in amps
echo "ups_output_amps,Hostname=$HOSTNAME value=$OUTPUTAMPS" >> /tmp/influx_write
echo "ups_battery_temp,Hostname=$HOSTNAME value=$BATTERYTEMP" >> /tmp/influx_write
echo "ups_battery_voltage,Hostname=$HOSTNAME value=$BATTERYVOLT" >> /tmp/influx_write


# post the data to the database
POST="curl -i -XPOST \""$2\"" --data-binary @/tmp/influx_write"
eval $POST

# clean up the processed files.
rm /tmp/influx_write

